# Generated by Django 4.2.5 on 2023-11-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("role", "0003_remove_accessrole_company_id_accessrole_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrole",
            name="org_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="accessrole",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="accessrole",
            unique_together={("name", "org_name")},
        ),
    ]
