# Generated by Django 4.2.5 on 2023-10-18 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_company_invite_type"),
        ("client", "0002_alter_client_company_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="company_id",
        ),
        migrations.AddField(
            model_name="client",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="company.company",
            ),
        ),
    ]
