# Generated by Django 4.2.5 on 2023-11-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_company_invite_type"),
        ("client", "0003_remove_client_company_id_client_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("name", "company")},
        ),
    ]
