# Generated by Django 4.2.4 on 2023-09-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='company',
        ),
    ]
