# Generated by Django 4.2.4 on 2023-09-15 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_invitation_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='company_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
