# Generated by Django 4.2.5 on 2023-09-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_invitation_company_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="invite_link",
            field=models.URLField(blank=True, default=""),
        ),
    ]
