# Generated by Django 4.2.5 on 2023-11-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_company_invite_type"),
        ("department", "0002_remove_department_company_id_department_company"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={},
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("name", "company")},
        ),
    ]
