# Generated by Django 4.2.5 on 2023-09-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_alter_company_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="invite_link",
            field=models.URLField(blank=True, default=""),
        ),
    ]
