# Generated by Django 4.2.5 on 2023-11-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="color_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
