# Generated by Django 4.2.5 on 2023-12-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_project_color_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="color_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VARIABLE", "Variable By Hour"),
                    ("FIXED", "Fixed Fee"),
                    ("NON_BILLABLE", "Non Billable"),
                ],
                default=None,
                max_length=40,
                null=True,
            ),
        ),
    ]
