# Generated by Django 4.2.5 on 2023-12-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_alter_project_color_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="color_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("#FF7034", "Orange"),
                    ("#57f287", "Green"),
                    ("#7FFFD4", "Aqua"),
                    ("#4169e1", "Blue"),
                    ("#9370DB", "Purple"),
                    ("#BA55D3", "Magenta"),
                    ("#FF0000", "Red"),
                    ("#D3D3D3", "Gray"),
                ],
                default=None,
                max_length=40,
                null=True,
            ),
        ),
    ]
