# Generated by Django 4.2.5 on 2023-12-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_alter_project_color_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="color_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("#fa6400cc", "Orange"),
                    ("#1e8c0acc", "Green"),
                    ("#3ca0c8cc", "Aqua"),
                    ("#004696cc", "Blue"),
                    ("#78328ccc", "Purple"),
                    ("#d22864cc", "Magenta"),
                    ("#d20a0acc", "Red"),
                    ("#888888cc", "Gray"),
                ],
                default=None,
                max_length=40,
                null=True,
            ),
        ),
    ]
