# Generated by Django 4.2.5 on 2023-11-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0004_schedule_schedule_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
