# Generated by Django 4.2.5 on 2023-11-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
            },
        ),
        migrations.AddField(
            model_name="team",
            name="emp_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
